### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by RaphaRC4** [VitalikObject/brawl-stars-server#4]
C:\Users\Raphael\Desktop\brawl-stars-server-main\src>python main.py
[INFO] Server started! Ip: 0.0.0.0, Port: 9339
[INFO] New connection! Ip: 192.168.178.36
[INFO] Received packet! Id: 18101
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Raphael\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\Raphael\Desktop\brawl-stars-server-main\src\main.py", line 73, in run
    message.process()
  File "C:\Users\Raphael\Desktop\brawl-stars-server-main\src\Packets\Messages\Client\Login.py", line 47, in process
    LoginOk(self.client, self.player).send()
  File "C:\Users\Raphael\Desktop\brawl-stars-server-main\src\Utils\Writer.py", line 34, in send
    self.encode()
  File "C:\Users\Raphael\Desktop\brawl-stars-server-main\src\Packets\Messages\Server\LoginOk.py", line 15, in encode
    self.writeInt(self.player.LowID)
  File "C:\Users\Raphael\Desktop\brawl-stars-server-main\src\Utils\Writer.py", line 8, in writeInt
    self.buffer += data.to_bytes(length, 'big')
OverflowError: int too big to convert

**Comment by VitalikObject** [comment]
Try to delete all data from "data.db"

**Comment by RaphaRC4** [comment]
> Try to delete all data from "data.db"

PS C:\Users\Raphael\Desktop\brawl-stars-server-main\src> python main.py
Traceback (most recent call last):
  File "main.py", line 93, in <module>
    server.start()
  File "main.py", line 29, in start
    os.mknod('./data.db') # create database file if does not exist
AttributeError: module 'os' has no attribute 'mknod'
PS C:\Users\Raphael\Desktop\brawl-stars-server-main\src>

Not working

**Comment by VitalikObject** [comment]
> > Try to delete all data from "data.db"
> 
> PS C:\Users\Raphael\Desktop\brawl-stars-server-main\src> python main.py
> Traceback (most recent call last):
>   File "main.py", line 93, in <module>
>     server.start()
>   File "main.py", line 29, in start
>     os.mknod('./data.db') # create database file if does not exist
> AttributeError: module 'os' has no attribute 'mknod'
> PS C:\Users\Raphael\Desktop\brawl-stars-server-main\src>
> 
> Not working

Why you delete data.db? You must clear it, remove all text from it.
